name: Publish to NPM RC

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - "release-*"

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - if: github.event_name == 'push'
        uses: actions/checkout@v4
      - if: github.event_name == 'pull_request'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: 22.11.0
      - name: Download & Build Icons
        run: npm ci --progress=false && npm i @iconscout/unicons@latest && npm run generate
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GH_AUTH_TOKEN }}
          title: Updated Icons
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
